---
theme: jekyll-theme-cayman
title: Brett W. Byron
defaults:
  scope:
    path: ""
    type: ""
  values:
    author: Brett Byron
    category: Brett W. Byron
sass:
  style: compressed
  sass_dir: _sass
---
